name: marakiib_app
description: "A new Flutter project."
publish_to: 'none'

version: 8.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.1.1
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  hugeicons: ^0.0.11
  intl: ^0.20.2
  l10n_flutter: ^1.0.7
  latlong2: ^0.9.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  cupertino_icons: ^1.0.8
  fl_country_code_picker: ^0.1.9+1
  country_picker: ^2.0.27
  photo_view: ^0.15.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  animated_snack_bar: ^0.4.0
  google_maps_flutter: ^2.13.1
  top_snackbar_flutter: ^3.3.0
  flutter_spinkit: ^5.2.2
  timezone: ^0.10.0

  connectivity_plus: ^7.0.0
  http: ^1.4.0
  lottie: ^3.3.0
  flutter_credit_card: ^4.1.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.1
  webview_flutter_wkwebview: ^3.23.0
  google_sign_in: ^7.2.0
  app_links: ^6.4.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  flutter_html: ^3.0.0
  facebook_app_events: ^0.24.0



dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100

# Add flutter_launcher_icons configuration at the bottom
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.png" # <-- replace with your icon path